[mantra-dukong]
network_name = "mantra-dukong"
chain_id = "mantra-dukong-1"
default_rpc = "https://rpc.dukong.mantrachain.io:443"
default_gas_price = 0.01
default_gas_adjustment = 1.5
native_denom = "uom"
evm_rpc_url = "https://evm.dukong.mantrachain.io"
evm_ws_url = "https://evm.dukong.mantrachain.io/ws"
evm_chain_id = 5887  # EVM chain ID 